Repository kuberMAPtes/noon-main-client-server, pull requests merged in 2024-06, with the labels that each got.

#3 Z ral dog/#2/chat UI
  package-lock.json
  package.json
  src/App.js
  src/index.js
  src/pages/Chat/ChatRoomCreation.css
  src/pages/Chat/Chatroom.css
  src/pages/Chat/Chatroom.js
  src/pages/Chat/ChatroomCreation.js
  src/pages/Chat/MyChatroomList.css
  src/pages/Chat/MyChatroomList.js
  src/pages/Chat/TEST/Chat_TEST.js
  src/utils/api.js
Labels: feat

#11 feat: 지도 UI 구현
  .gitignore
  package-lock.json
  package.json
  public/image/marker.png
  public/index.html
  src/components/map/FetchTypeToggle.js
  src/components/map/SearchWindow.js
  src/pages/Map/map.js
  src/pages/map/BMap.js
  src/routes/AppRoutes.jsx
Labels: feat, chore

#17 feat: 통합 검색창 구현
  src/components/common/SearchWindow.js
  src/components/map/SearchWindow.js
  src/components/search/BuildingSearchResult.js
  src/components/search/ChatroomSearchResult.js
  src/components/search/FeedSearchResult.js
  src/components/search/MemberSearchResult.js
  src/components/search/SearchModeTab.js
  src/pages/map/BMap.js
  src/pages/search/Search.js
  src/routes/AppRoutes.jsx
Labels: feat

#20 feat: 환경설정 변경 화면 구현
  src/components/setting/ButtonGroup.js
  src/pages/setting/MemberSetting.js
  src/pages/setting/setting.js
  src/routes/AppRoutes.jsx
Labels: feat

#26 feat: 운영정보 보기 구현
  src/pages/setting/MemberSetting.js
Labels: feat

#29 feat : 피드 관련 View에 대한 틀 추가
  .github/ISSUE_TEMPLATE/기본-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/버그-리포트.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/pages/Feed/feed.js
  src/pages/feed/FeedDetail.jsx
  src/pages/feed/FeedForm.jsx
  src/pages/feed/FeedList.jsx
  src/pages/feed/component/FeedDetailComponent.jsx
  src/pages/feed/component/FeedFormComponent.jsx
  src/pages/feed/component/FeedItem.jsx
  src/pages/feed/css/FeedDetail.css
  src/pages/feed/css/FeedForm.css
  src/pages/feed/css/FeedItem.css
  src/pages/feed/css/FeedList.css
  src/routes/AppRoutes.jsx
Labels: feat

#31 refactor: component에 있는 공통적이지 않은 JSX 컴포넌트 pages 아래로 이동
  src/components/common/SearchWindow.jsx
  src/pages/CustomerSupport/AddNoticeView.js
  src/pages/map/BMap.jsx
  src/pages/map/component/FetchTypeToggle.jsx
  src/pages/search/Search.jsx
  src/pages/search/component/BuildingSearchResult.jsx
  src/pages/search/component/ChatroomSearchResult.jsx
  src/pages/search/component/FeedSearchResult.jsx
  src/pages/search/component/MemberSearchResult.jsx
  src/pages/search/component/SearchModeTab.jsx
  src/pages/setting/MemberSetting.jsx
  src/pages/setting/component/ButtonGroup.jsx
Labels: refactor

#33 building -> Building2
  src/pages/building/Building2.js
  src/routes/AppRoutes.jsx
Labels: hotfix

#42 feat : 임시 상단바 추가, 상단바 추가 한정 글꼴 추가, 피드 관련 View에 Axios 임시 적용, 피드 목록 무한스크롤
  src/assets/css/BasicNavbar.css
  src/assets/css/font.css
  src/components/common/BasicNavbar.jsx
  src/fonts/Batang_Bold.woff
  src/fonts/Batang_Regular.woff
  src/fonts/Title_Bold.woff
  src/fonts/Title_Light.woff
  src/pages/feed/FeedDetail.jsx
  src/pages/feed/FeedDetailPage.jsx
  src/pages/feed/FeedFormPage.jsx
  src/pages/feed/FeedList.jsx
  src/pages/feed/FeedListPage.jsx
  src/pages/feed/FeedPages.jsx
  src/pages/feed/component/CategoryButtonComponent.jsx
  src/pages/feed/component/FeedDetail.jsx
  src/pages/feed/component/FeedForm.jsx
  src/pages/feed/component/FeedItem.jsx
  src/pages/feed/component/FeedNotFound.jsx
  src/pages/feed/component/SlideUpModal.jsx
  src/pages/feed/css/FeedNotFound.css
  src/pages/feed/css/SlideUpModal.css
  src/routes/AppRoutes.jsx
Labels: feat

#39 feat: 지도에 여러 조작 구현
  src/pages/map/BMap.jsx
  src/pages/map/component/FetchTypeToggle.jsx
  src/pages/setting/MemberSetting.jsx
  src/util/constants.js
  src/util/statusCodeUtil.js
Labels: feat

#46 feat: 지도 기능 완성
  package-lock.json
  src/pages/map/BMap.jsx
  src/pages/map/component/FetchTypeToggle.jsx
  src/pages/map/contant/markerHtml.js
Labels: feat

#50 design: 환경설정 화면 디자인
  src/pages/setting/MemberSetting.jsx
  src/pages/setting/component/ButtonGroup.jsx
  src/pages/setting/component/OpInfoModal.jsx
  src/pages/setting/component/PublicRangeDropdown.jsx
  src/pages/setting/constants/termsAndPolicy.js
  src/pages/setting/constants/termsOfUse.js
  src/pages/setting/css/MemberSetting.css
  src/pages/setting/css/OpInfoModal.css
  src/routes/AppRoutes.jsx
Labels: feat, design

#53 design: 지도 화면 디자인
  public/image/my-location.png
  src/assets/css/module/map/BMap.css
  src/components/common/Footer.jsx
  src/components/common/SearchBar.jsx
  src/components/common/SearchWindow.jsx
  src/pages/map/BMap.jsx
  src/pages/map/component/FetchTypeToggle.jsx
  src/pages/map/contant/markerHtml.js
  src/pages/search/Search.jsx
Labels: feat, design

#59 feat: 통합 검색창에서 데이터 요청
  .gitignore
  src/pages/search/Search.jsx
  src/pages/search/axios/searchBuilding.js
  src/pages/search/axios/searchChatroom.js
  src/pages/search/axios/searchFeed.js
  src/pages/search/axios/searchMember.js
  src/pages/search/component/BuildingSearchResult.jsx
  src/pages/search/component/ChatroomSearchResult.jsx
  src/pages/search/component/FeedSearchResult.jsx
  src/pages/search/component/MemberSearchResult.jsx
Labels: feat

#62 design: 통합 검색 데이터 반영 및 디자인
  public/image/address.png
  public/image/chat-participants.png
  public/image/chat.png
  public/image/clock.png
  public/image/write.png
  public/index.html
  src/assets/assets.js
  src/assets/css/module/search/Search.css
  src/assets/css/module/search/component/BuildingSearchResult.css
  src/assets/css/module/search/component/ChatroomSearchResult.css
  src/assets/css/module/search/component/FeedSearchResult.css
  src/assets/css/module/search/component/MemberSearchResult.css
  src/assets/css/module/search/component/SearchModeTab.css
  src/assets/image/image.js
  src/lib/axios_api.js
  src/pages/search/Search.jsx
  src/pages/search/component/BuildingSearchResult.jsx
  src/pages/search/component/ChatroomSearchResult.jsx
  src/pages/search/component/FeedSearchResult.jsx
  src/pages/search/component/MemberSearchResult.jsx
  src/pages/search/component/SearchModeTab.jsx
Labels: design

#79 hotfix, feat : 피드 태그가 없을 때 undefined 예외 처리 / 피드 목록 및 상세보기에 대한 추가 작업
  src/App.js
  src/components/common/BasicNavbar.jsx
  src/pages/feed/FeedBuildingListPage.jsx
  src/pages/feed/FeedDetailPage.jsx
  src/pages/feed/FeedListHomePage.jsx
  src/pages/feed/FeedListPage.jsx
  src/pages/feed/FeedPages.jsx
  src/pages/feed/component/FeedDetail/FeedDetail.jsx
  src/pages/feed/component/FeedDetail/LikedUsersList.jsx
  src/pages/feed/component/FeedList/FeedItem.jsx
  src/pages/feed/component/FeedList/FeedPopularyRanking.jsx
  src/pages/feed/util/Navigator.js
Labels: feat, hotfix

#85 feat: Search 페이지 다른 컴포넌트로 이동/무한 스크롤
  src/assets/css/module/search/Search.css
  src/components/common/Footer.jsx
  src/components/common/SearchBar.jsx
  src/pages/map/BMap.jsx
  src/pages/search/Search.jsx
  src/pages/search/axios/searchBuilding.js
  src/pages/search/axios/searchChatroom.js
  src/pages/search/axios/searchFeed.js
  src/pages/search/axios/searchMember.js
  src/pages/search/component/BuildingSearchResult.jsx
  src/pages/search/component/ChatroomSearchResult.jsx
  src/pages/search/component/FeedSearchResult.jsx
  src/pages/search/component/MemberSearchResult.jsx
Labels: feat

#90 feat: 지도 디자인 및 기능 추가
  public/image/popular-bulilding.png
  public/image/subscription-bulilding.png
  src/assets/css/module/map/BMap.css
  src/assets/css/module/map/BMap.module.css
  src/components/common/SearchBar.jsx
  src/lib/axiosInstance.js
  src/lib/axios_api.js
  src/pages/map/BMap.jsx
  src/pages/map/component/FetchTypeToggle.jsx
  src/redux/slices/currentMapStateSlice.js
  src/redux/store.js
Labels: feat, refactor, design

#92 feat, fix : 피드 내 산재되어 있던 버그 해결 여러 기능 추가
  src/pages/feed/FeedDetailPage.jsx
  src/pages/feed/FeedFormPage.jsx
  src/pages/feed/FeedPages.jsx
  src/pages/feed/component/Common/CheckModal.jsx
  src/pages/feed/component/FeedChart/FeedForm.jsx
  src/pages/feed/component/FeedDetail/FeedDetail.jsx
  src/pages/feed/component/FeedForm.jsx
  src/pages/feed/component/FeedForm/CategoryButtonComponent.jsx
  src/pages/feed/component/FeedForm/FeedForm.jsx
  src/pages/feed/component/FeedForm/SlideUpModal.jsx
  src/pages/feed/util/Navigator.js
  src/routes/AppRoutes.jsx
Labels: feat, fix

#99 feat: 건물 위키 페이지 구현
  src/assets/css/module/building/EditBuildingWiki.module.css
  src/pages/building/EditBuildingWiki.jsx
  src/pages/building/GetBuildingWiki.jsx
  src/routes/AppRoutes.jsx
Labels: feat

#101 design: 지도 색상 디자인
  src/assets/css/module/map/BMap.css
  src/assets/css/module/map/BMap.module.css
  src/pages/map/BMap.jsx
Labels: design

#107 design : 빌딩 프로필, 고객지원 디자인 수정
  src/components/common/Footer.jsx
  src/pages/CustomerSupport/GetChatbot.jsx
  src/pages/CustomerSupport/GetNoticeList.jsx
  src/pages/CustomerSupport/GetReportList.jsx
  src/pages/CustomerSupport/ListImages.jsx
  src/pages/CustomerSupport/components/Support.jsx
  src/pages/CustomerSupport/css/customerSupport.css
  src/pages/building/components/TabNavigation.jsx
  src/pages/building/css/tab-navigation.css
  src/routes/AppRoutes.jsx
Labels: design

#105 feat : 피드에 대한 상세 기능 추가
  src/components/common/BasicNavbar.jsx
  src/components/css/BasicNavbar.css
  src/pages/feed/FeedListHomePage.jsx
  src/pages/feed/FeedListPage.jsx
  src/pages/feed/FeedPages.jsx
  src/pages/feed/component/FeedDetail/FeedDetail.jsx
  src/pages/feed/component/FeedDetail/LikedUsersList.jsx
  src/pages/feed/component/FeedForm/FeedForm.jsx
  src/pages/feed/component/FeedList/FeedItem.jsx
  src/pages/feed/util/AttachmentGetter.js
  src/pages/feed/util/renderFeedTextWithLink.js
  src/routes/AppRoutes.jsx
Labels: feat

#108 fix: Footer.jsx에서 의도치 않게 삭제된 코드 복구
  src/components/common/Footer.jsx
Labels: fix

#109 fix: ProfileBody 에러 픽스
  src/pages/member/component/profile/ProfileBody.jsx
Labels: fix

#112 feat: 지도 관련 기능 추가 및 리팩토링
  src/pages/map/BMap.jsx
  src/redux/slices/currentMapStateSlice.js
Labels: feat, refactor

#114 refactor: 검색 화면 리팩토링
  src/assets/css/module/search/Search.css
  src/assets/css/module/search/component/SearchModeTab.css
  src/pages/search/Search.jsx
  src/pages/search/component/SearchModeTab.jsx
Labels: refactor

#116 refactor: axios 리팩토링
  src/lib/axiosInstance.js
  src/lib/axios_api.js
Labels: refactor

#124 design: 환경설정 페이지 디자인 리팩토링
  src/pages/setting/MemberSetting.jsx
  src/pages/setting/css/MemberSetting.css
Labels: refactor, design

#132 refactor: 지도 컴포넌트 리팩토링
  src/pages/map/BMap.jsx
  src/routes/AppRoutes.jsx
Labels: feat, refactor

#134 feat : 투표 게시판 추가, 기본적인 기능 추가
  src/pages/feed/component/FeedDetail/FeedDetail.jsx
  src/pages/feed/component/FeedForm/FeedVote.jsx
  src/pages/feed/component/FeedList/FeedItem.jsx
Labels: feat

#136 refactor: 건물 위키 페이지 디자인 및 기능 리팩토링
  src/assets/css/module/building/EditBuildingWiki.module.css
  src/assets/css/module/building/wiki/EditBuildingWiki.module.css
  src/assets/css/module/building/wiki/GetBuildingWiki.css
  src/assets/css/module/building/wiki/GetBuildingWiki.module.css
  src/pages/building/GetBuildingWiki.jsx
  src/pages/building/components/BuildingInfo.jsx
  src/pages/building/wiki/EditBuildingWiki.jsx
  src/pages/building/wiki/GetBuildingWiki.jsx
  src/routes/AppRoutes.jsx
Labels: refactor

#138 refactor: token 재발급 로직
  src/lib/axiosInstance.js
  src/lib/axios_api.js
Labels: refactor

#142 fix: 장소 검색 시 에러 발생 픽스
  src/pages/map/BMap.jsx
Labels: fix

#155 feat : 버그 수정, 요구사항 반영, 이벤트 피드 관련 로직 구현 중
  package.json
  src/pages/feed/FeedMegaphoneFormPage.jsx
  src/pages/feed/component/FeedDetail/FeedDetail.jsx
  src/pages/feed/component/FeedForm/FeedForm.jsx
  src/pages/feed/component/FeedForm/SlideUpModal.jsx
  src/pages/feed/component/FeedList/FeedCalendar.jsx
  src/pages/feed/util/FormatDate.js
  src/pages/feed/util/Navigator.js
Labels: feat, fix

#156 feat: footerEnabled reducer 정의
  package-lock.json
  src/App.js
  src/pages/building/wiki/EditBuildingWiki.jsx
  src/pages/building/wiki/GetBuildingWiki.jsx
  src/pages/map/BMap.jsx
  src/pages/search/Search.jsx
  src/pages/setting/MemberSetting.jsx
  src/redux/slices/footerEnabledSlice.js
  src/redux/store.js
Labels: feat

#159 feat: 마커 표시 모드에 따라 마커에 표시되는 데이터가 달라집니다.
  package-lock.json
  src/assets/css/module/map/MarkerModeButtonGroup.module.css
  src/pages/map/BMap.jsx
  src/pages/map/component/FetchTypeToggle.jsx
  src/pages/map/component/MarkerModeButtonGroup.jsx
  src/pages/map/contant/markerHtml.js
Labels: feat

#163 fix: 현재 로그인한 회원의 환경설정 정보 제공
  src/pages/setting/MemberSetting.jsx
Labels: fix

#165 feat: 건물 클릭 시 건물 프로필로 이동
  src/pages/map/BMap.jsx
Labels: feat

#170 feat : 회원 프로필 내 피드 목록 보기 관련 버그 정리
  src/pages/feed/FeedDetailPage.jsx
  src/pages/feed/FeedFormPage.jsx
  src/pages/feed/FeedListPage.jsx
  src/pages/feed/FeedMegaphoneFormPage.jsx
  src/pages/feed/FeedPages.jsx
  src/pages/feed/FeedVoteFormPage.jsx
  src/pages/feed/component/FeedForm/FeedForm.jsx
  src/pages/feed/component/FeedList/FeedDropdown.jsx
Labels: feat, fix

#161 feat: 검색 화면 default 탭 설정
  src/pages/search/Search.jsx
Labels: feat

#174 fix : 요구사항 변경 및 버그 수정
  src/pages/feed/FeedDetailPage.jsx
  src/pages/feed/component/FeedDetail/FeedDetail.jsx
  src/pages/feed/component/FeedForm/FeedForm.jsx
  src/routes/AppRoutes.jsx
Labels: fix

#172 feat: Loading Spinner 추가
  src/assets/css/module/map/BMap.module.css
  src/pages/building/wiki/GetBuildingWiki.jsx
  src/pages/map/BMap.jsx
  src/pages/map/contant/markerHtml.js
  src/pages/search/Search.jsx
  src/pages/setting/MemberSetting.jsx
Labels: feat

#177 fix : 상단바 추가, 블러 이미지 적용 및 버그 수정
  src/pages/feed/FeedBuildingListPage.jsx
  src/pages/feed/FeedChartPage.jsx
  src/pages/feed/FeedDetailPage.jsx
  src/pages/feed/FeedFormPage.jsx
  src/pages/feed/FeedListHomePage.jsx
  src/pages/feed/FeedMegaphoneFormPage.jsx
  src/pages/feed/FeedVoteFormPage.jsx
  src/pages/feed/component/FeedForm/FeedForm.jsx
  src/pages/feed/component/FeedForm/FeedMegaphoneForm.jsx
  src/pages/feed/component/FeedForm/FeedVoteForm.jsx
  src/pages/feed/component/FeedList/FeedItem.jsx
Labels: fix

#180 feat: 지도 관련 여러 기능 추가
  src/assets/css/module/map/BMap.module.css
  src/pages/map/BMap.jsx
  src/pages/map/contant/markerHtml.js
Labels: feat

#182 feat: 지도 화면에서 건물 합치기 기능 사용 가능
  public/image/not-activated-building.png
  src/assets/css/module/map/BMap.module.css
  src/pages/map/BMap.jsx
  src/pages/map/contant/markerHtml.js
Labels: feat

#185 feat: 사이트 타이틀 및 아이콘 지정
  public/index.html
Labels: feat

#190 feat : 각종 알림, design : 신고하기, 채팅목록, fix : 건물 프로필 구독상태
  src/pages/CustomerSupport/AddReport.jsx
  src/pages/CustomerSupport/GetNotice.jsx
  src/pages/CustomerSupport/GetReport.jsx
  src/pages/building/GetBuilding.jsx
  src/pages/building/components/BuildingInfo.jsx
  src/pages/building/components/ChatroomList.jsx
  src/pages/building/components/TabNavigation.jsx
  src/pages/building/components/WantBuildingProfile.jsx
Labels: feat, design, hotfix
