Repository kuberMAPtes/noon-main-client-server, pull requests merged in 2024-07, with the labels that each got.

#192 fix, style : "아무튼 다 고침"
  src/pages/feed/FeedBuildingListPage.jsx
  src/pages/feed/FeedChartPage.jsx
  src/pages/feed/FeedListHomePage.jsx
  src/pages/feed/FeedListPage.jsx
  src/pages/feed/component/FeedChart/FeedCntByTag.jsx
  src/pages/feed/component/FeedChart/FeedForm.jsx
  src/pages/feed/component/FeedDetail/FeedDetail.jsx
  src/pages/feed/component/FeedDetail/LikedUsersList.jsx
  src/pages/feed/component/FeedForm/FeedForm.jsx
  src/pages/feed/component/FeedForm/FeedMegaphoneForm.jsx
  src/pages/feed/component/FeedForm/FeedVote.jsx
  src/pages/feed/component/FeedForm/FeedVoteForm.jsx
  src/pages/feed/component/FeedForm/VotePreview.jsx
  src/pages/feed/component/FeedList/FeedCalendar.jsx
  src/pages/feed/component/FeedList/FeedDisplayBoard.jsx
  src/pages/feed/component/FeedList/FeedDropdown.jsx
  src/pages/feed/component/FeedList/FeedItem.jsx
  src/pages/feed/component/FeedList/FeedPopularyRanking.jsx
  src/pages/feed/component/FeedNotFound.jsx
  src/pages/feed/css/FeedCalender.css
  src/pages/feed/css/FeedDisplayBoard.css
  src/pages/feed/css/FeedForm.css
  src/pages/feed/css/FeedForm/FeedForm.module.css
  src/pages/feed/css/FeedForm/FeedVote.module.css
  src/pages/feed/css/FeedItemAndDetail.module.css
  src/pages/feed/css/FeedList/FeedCalender.css
  src/pages/feed/css/FeedList/FeedDisplayBoard.css
  src/pages/feed/css/FeedList/FeedDropdown.module.css
  src/pages/feed/css/FeedList/FeedPopularyRanking.module.css
  src/pages/feed/css/common/FeedItemAndDetail.module.css
  src/pages/feed/css/common/FeedNotFound.css
Labels: fix, style

#194 feat: zoom level 13 이하일 경우 구독 마커 10개만 표시
  src/pages/map/BMap.jsx
Labels: feat

#196 fix : 피드 제목이 사라지는 현상 해결
  src/pages/feed/FeedListHomePage.jsx
  src/pages/feed/component/FeedForm/FeedForm.jsx
  src/pages/feed/component/FeedList/FeedItem.jsx
  src/pages/feed/css/common/FeedItemAndDetail.module.css
Labels: fix

#199 fix : 피드 관련 세부 사항 변경
  src/pages/feed/FeedBuildingListPage.jsx
  src/pages/feed/FeedListPage.jsx
  src/pages/feed/component/FeedDetail/FeedDetail.jsx
  src/pages/feed/component/FeedList/FeedCalendar.jsx
  src/pages/feed/component/FeedList/FeedItem.jsx
  src/pages/feed/component/FeedList/FeedPopularyRanking.jsx
  src/pages/feed/css/FeedList/FeedCalender.css
  src/pages/feed/css/FeedList/FeedPopularyRanking.module.css
Labels: fix

#200 fix: 채팅방 마커 안 사라지는 거 고침
  src/pages/map/BMap.jsx
Labels: fix

#205 design: 맵 아이콘 변경
  public/image/not-activated-building.png
  public/image/popular-bulilding.png
  public/image/subscription-bulilding.png
  src/pages/map/contant/markerHtml.js
Labels: design

#207 refactor: 건물 합치기 버튼 내 구독 목록 볼 땐 안 보이게 세팅
  src/pages/map/BMap.jsx
Labels: refactor

#214 design, fix : 전체적인 디자인 수정
  src/pages/feed/FeedBuildingListPage.jsx
  src/pages/feed/component/FeedDetail/FeedDetail.jsx
  src/pages/feed/component/FeedList/FeedCalendar.jsx
  src/pages/feed/component/FeedList/FeedItem.jsx
  src/pages/feed/css/common/FeedButton.module.css
  src/pages/feed/css/common/FeedItemAndDetail.module.css
  src/pages/feed/util/FormatDate.js
  src/pages/feed/util/Navigator.js
Labels: fix, design

#212 design: 건물 위키 디자인 수정
  src/assets/css/module/building/wiki/EditBuildingWiki.module.css
  src/assets/css/module/building/wiki/GetBuildingWiki.css
  src/assets/css/module/building/wiki/GetBuildingWiki.module.css
  src/pages/building/wiki/EditBuildingWiki.jsx
  src/pages/building/wiki/GetBuildingWiki.jsx
Labels: feat, design

#213 design: 검색 화면 디자인
  src/assets/css/module/search/Search.css
  src/assets/css/module/search/component/BuildingSearchResult.module.css
  src/assets/css/module/search/component/ChatroomSearchResult.css
  src/assets/css/module/search/component/ChatroomSearchResult.module.css
  src/assets/css/module/search/component/FeedSearchResult.module.css
  src/assets/css/module/search/component/MemberSearchResult.css
  src/assets/css/module/search/component/MemberSearchResult.module.css
  src/pages/search/Search.jsx
  src/pages/search/component/BuildingSearchResult.jsx
  src/pages/search/component/ChatroomSearchResult.jsx
  src/pages/search/component/FeedSearchResult.jsx
  src/pages/search/component/MemberSearchResult.jsx
  src/util/stringUtil.js
Labels: feat, design

#222 design : 피드 작성 폼 전체적인 디자인 변경
  src/pages/feed/FeedBuildingListPage.jsx
  src/pages/feed/FeedFormPage.jsx
  src/pages/feed/FeedListHomePage.jsx
  src/pages/feed/FeedMegaphoneFormPage.jsx
  src/pages/feed/FeedVoteFormPage.jsx
  src/pages/feed/component/FeedDetail/FeedDetail.jsx
  src/pages/feed/component/FeedForm/FeedForm.jsx
  src/pages/feed/component/FeedForm/FeedMegaphoneForm.jsx
  src/pages/feed/component/FeedForm/FeedVote.jsx
  src/pages/feed/component/FeedForm/FeedVoteForm.jsx
  src/pages/feed/component/FeedForm/FloatingButtons.jsx
  src/pages/feed/component/FeedForm/SlideUpModal.jsx
  src/pages/feed/component/FeedList/FeedCalendar.jsx
  src/pages/feed/component/FeedList/FeedItem.jsx
  src/pages/feed/component/FeedList/FeedPopularyRanking.jsx
  src/pages/feed/css/FeedForm/FeedForm.module.css
  src/pages/feed/css/FeedForm/FeedVote.module.css
  src/pages/feed/css/FeedForm/FloatingButton.module.css
  src/pages/feed/css/FeedList/FeedCalender.css
  src/pages/feed/css/common/FeedButton.module.css
  src/pages/feed/css/common/FeedItemAndDetail.module.css
  src/pages/feed/css/common/FeedLine.module.css
Labels: design

#219 design: 환경설정 디자인
  public/image/subscription-bulilding.png
  src/lib/axiosInstance.js
  src/lib/axios_api.js
  src/pages/search/Search.jsx
  src/pages/setting/MemberSetting.jsx
  src/pages/setting/component/OpInfoModal.jsx
  src/pages/setting/constants/termsOfUse.js
  src/pages/setting/css/MemberSetting.css
  src/pages/setting/css/OpInfoModal.css
Labels: feat, refactor, design

#221 feat: 자동 검색 구현
  src/components/common/SearchBar.jsx
  src/pages/search/Search.jsx
  src/pages/search/component/FeedSearchResult.jsx
  src/util/stringUtil.js
Labels: feat

#231 design : 디자인 수정
  package-lock.json
  src/pages/feed/component/FeedDetail/FeedDetail.jsx
  src/pages/feed/component/FeedForm/FeedForm.jsx
  src/pages/feed/component/FeedForm/FeedMegaphoneForm.jsx
  src/pages/feed/component/FeedForm/FeedVoteForm.jsx
  src/pages/feed/component/FeedList/FeedCalendar.jsx
  src/pages/feed/component/FeedList/FeedItem.jsx
  src/pages/feed/css/FeedForm/FeedForm.module.css
  src/pages/feed/css/common/FeedItemAndDetail.module.css
Labels: design

#227 feat: 프로필 사진 URL이 존재하지 않을 경우 기본 이미지로 대체
  src/assets/css/module/map/BMap.css
  src/assets/css/module/map/BMap.module.css
  src/assets/css/module/search/Search.css
  src/assets/css/module/search/Search.module.css
  src/assets/css/module/search/component/MemberSearchResult.module.css
  src/components/common/SearchBar.jsx
  src/pages/map/BMap.jsx
  src/pages/search/Search.jsx
  src/pages/search/axios/searchMember.js
  src/pages/search/component/MemberSearchResult.jsx
  src/pages/setting/MemberSetting.jsx
  src/pages/setting/css/MemberSetting.css
Labels: feat, design

#235 fix: 건물 등록됐는데 새로고침 안 하면 계속 등록되지 않은 건물 뜨는 버그
  src/pages/map/BMap.jsx
Labels: fix

#236 fix, design : 디자인 수정 및 잔버그 수정
  src/pages/feed/component/FeedDetail/FeedDetail.jsx
  src/pages/feed/component/FeedForm/FeedForm.jsx
  src/pages/feed/component/FeedForm/FeedVoteForm.jsx
  src/pages/feed/css/FeedForm/FeedForm.module.css
  src/pages/feed/css/common/FeedNotFound.css
  src/pages/feed/util/FormatDate.js
Labels: feat, fix
